### ISSUE TITLE
Buffer wiped out from search results

### ISSUE THREAD

**Issue by vito-c** [scalameta/coc-metals#100]
**Describe the bug**

This happens for find references and jump to definitions when there are multiple search results.

1. Open a file (Foo.scala) and go to find references inside the project ( make sure there  are multiple references)
2. The windows change sizes and my current buffer (Foo.scala) is loaded with the search results from the plugin.
3. Foo.scala is set to unmodifable.
4. Select a search result.
5. buffer Foo.scala is blow away and all of my changes to Foo.scala are lost. 

This is a pretty serious bug seems like it might be coming from the coc plugin but i'm not sure.

**Installation:**

- macOS
- nvim latest
- coc-metals extension version: 
- Metals version: `0.8.0+313-40759eb6-SNAPSHOT`
- scala 2.11
- sbt 0.13

**Comment by ckipp01** [comment]
Hi @vito-c, thanks for reporting.

I'm unable to reproduce this locally. Are you able to provide a reproduction of some sort for this? The `coc-references` which you're referring to is a pretty core part of coc.nvim and not specific to coc-metals at all. I'd be very surprised to see this happen as I'm assuming everyone would be complaining about it.

> Foo.scala is set to unmodifable.

Do you actually mean `nomodifiable`? Or are you just saying that you're no longer in insert mode when you do this? I'm a bit confused by this as I don't see a reason to turn on `nomodifiable` when you are working in a buffer and trying to find references (if you really do mean `nomodifiable`.

Also, 0.8.1 of Metals is out, so you'll want to upgrade to that. I know it's not always in your control, but your also using an extremely old version of sbt. You may want to put in some effort to bump your version of Scala and sbt to give you a bit smoother of an experience.

**Comment by vito-c** [comment]
I just ran `CocList commands` and it did the same thing! loaded all the selections into my current buffer (Foo.scala) and then set it to `nomodifiable`

**Comment by vito-c** [comment]
This was due to a sneaky autocommand I had hidden in my vimrc. :(
```
    augroup autotag " {{{
        autocmd!
        " need to cd to groot
        autocmd BufNewFile,BufRead,BufEnter * call UpdatePath()
    augroup END " }}}

    function! UpdatePath()
        let foo =  match(fnameescape(expand('%')), "fugitive://")
        if &buftype != 'terminal' && foo < 0
            set path&vim | let &path=rc#git#groot()['dir'] . '/**'
            execute 'cd' rc#git#groot()['dir']
        endif
    endfunction
```

**Comment by ckipp01** [comment]
> This was due to a sneaky autocommand I had hidden in my vimrc. :(

Glad you were able to figure it out!
