### ISSUE TITLE
Cannot find module 'metals-languageclient'

### ISSUE THREAD

**Issue by kushtal** [scalameta/coc-metals#114]
When I open any scala file I get the error:
[coc.nvim] Error on load extension coc-metals from /home/user/.config/coc/extensions/node_modules/coc-metals/lib/index.js: Error: Cannot find module 'metals-languageclient'

**To Reproduce** Steps to reproduce the behavior:
1. Go to scala project folder
2. Run 'nvim .'
3. Open any scala file

**Installation:**
- Operating system: Linux (LUbuntu 18.04 LTS)
- nvim version: v0.5.0
- coc-metals extension version: 0.7.2
- node version: v8.10.0

**Comment by ckipp01** [comment]
Hey @kushtal, thanks for reporting. As mentioned on gitter, the first step is to ensure that yarn is working to install it correctly. Coc.nvim is doing a yarn install on coc-metals to ensure that it's installed correctly. The error you're getting makes it seem that that's not working as expected. If you can, go to `/home/user/.config/coc/extensions/node_modules/coc-metals` and do a yarn install. Make sure you have yarn available there and that the install works correctly. If not, report back with what you get.

**Comment by kushtal** [comment]
Thank you. Yesterday, when I did "yarn install" command in "coc-metals" folder than i got:
- 00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'

But now I get:
- error mkdirp@1.0.3: The engine "node" is incompatible with this module. Expected version ">=10". Got "8.10.0"

After update nodejs, It's ok. But now, when i open *.scala file I get these successful log messages:
- [coc.nvim] Downloading Metals v0.8.1
- [coc.nvim] Metals is Ready!
- [coc.nvim] Running sbt bloopInstall
and one failed message:
- [coc.nvim] Failed to connect with build server, no functionality will work. See logs for more details.

How can I read advanced nvim logs? When I try to do this as ":messages" than i got the same log messages .

**Comment by ckipp01** [comment]
Hi @kushtal, sorry for the delay, Like you already figured out, 8 is quite old, and won't work. I'd recommend trying to get to LTS. I should maybe put that in the docs. Glad you got it figured out.
