### ISSUE TITLE
Update notification disappears shortly after display

### ISSUE THREAD

**Issue by arbitrary-dev** [scalameta/coc-metals#139]
**Describe the bug**

When I start vim I get a short time flash of "You are running an out-of-date version of Metals…" and then it disappears with cursor still blocked awaiting for user input. Sometimes it reappears, sometimes not.

![notification](https://user-images.githubusercontent.com/6984946/77935277-e7b2ea80-72b9-11ea-874c-f45d5a7f75f2.jpg)

**Expected behavior**

Notification doesn't disappear until input provided.

**Installation:**

- Operating system: Linux
- Vim version:
  ```
  $ vim --version
  VIM - Vi IMproved 8.1 (2018 May 18, compiled Mar  4 2020 10:55:18)
  Included patches: 1-1486
  ```
- coc-metals extension version: 0.7.4
- Metals version:
  ```
   "metals.serverVersion": "0.8.1+19-04f10d20-SNAPSHOT"
  ```

**Search terms**

update notification disappear

**Comment by ckipp01** [comment]
Thanks for reporting!

You'll want to make sure you update everything. There is newer versions of Vim, coc-metals, and metals compared to what you have listed.

However, I'm able to reproduce this locally when using Vim rather then Nvim.

**Comment by ckipp01** [comment]
So the issue is right here:

https://github.com/scalameta/coc-metals/blob/5daf3b472c231a860c7bd0965eb558eaefce670c/src/utils.ts#L24-L52

However, the frustrating part is that this works just fine in Nvim, but in Vim for whatever reason the prompt closes seemingly as soon as any other status message comes in.

**Comment by ckipp01** [comment]
As a follow-up, I talked to the maintainers of coc.nvim about this today. It seems that in Vim, when another message is coming into the channel, just closes. There isn't a lot of ways around this. However, one thing that was mentioned was switching the api in coc.nvim to use `popup-menu`, which would work better in vim. For now, we are sort of blocked by this.

**Comment by ckipp01** [comment]
So a fix was already pushed up on the coc.nvim side for this today :) You can see it [here](https://github.com/neoclide/coc.nvim/commit/f589fa764399394e806de007d25c3f224faec8ec). I uses `popup-menu` when you're in vim. I've included an image to show what I mean.

<img width="1183" alt="Screenshot 2020-03-31 at 22 22 46" src="https://user-images.githubusercontent.com/13974112/78072020-b3652a00-739e-11ea-99e6-236549a551ef.png">

Until they do a release, you'll have to use the following to ensure you're building from source until they do a release.

```
" Or build from source code by use yarn: https://yarnpkg.com
Plug 'neoclide/coc.nvim', {'do': 'yarn install --frozen-lockfile'}
```

**Comment by mtvec** [comment]
I'm having exactly the same issue with the initial "import build" menu. Is `popup-menu` supposed to be used there as well?

- Vim: 8.2
- coc-metals: 1.0.11
- Metals: 0.10.9
- coc.nvim: 0.0.80

**Comment by ckipp01** [comment]
I @mtvec I'm actually not 100% sure. The "import build" message is actually a `window/showMessageRequest` that is sent from the server and coc.nvim directly handles this, so you'd have to ask over there or dig into their implementation for that.
