### ISSUE TITLE
Companion object apply signature

### ISSUE THREAD

**Issue by kuberlog** [scalameta/coc-metals#154]
Does this support showing the function signature for a CompanionObject.apply?

I can't seem to get that working, however I can get function signatures to display for standard functions, so I don't think I need to change configurations or anything.

**Comment by ckipp01** [comment]
Hi @kuberlog, thanks for the questions. Yes, doing a hover on the apply should work just fine. I've pasted in an image below to illustrate this.

<img width="463" alt="Screenshot 2020-04-05 at 09 34 47" src="https://user-images.githubusercontent.com/13974112/78469368-c9694680-7720-11ea-9913-9487dcfeeacc.png">

Do you maybe have a specific chunk of code this isn't working on that I could try to reproduce?

**Comment by ckipp01** [comment]
@kuberlog did you by chance have any more information on this?

**Comment by kuberlog** [comment]
Thanks for the response. I'll take a look at it tonight after my day job and see what I can come up with.

**Comment by ckipp01** [comment]
I'm going to go ahead and close this. @kuberlog if you can come up with a reproduction, feel free to drop it in here and I can open this back up. However, this should be working.
