### ISSUE TITLE
Renaming public members doesn't work in Vim

### ISSUE THREAD

**Issue by zsolt-donca** [scalameta/coc-metals#164]
**Describe the bug**
When I use the rename command on a public symbol, such as a class or a method, the references are updated only in the current file, and not across the project. This happens only if I use vim. I also tried with VSCode, and it seems to work fine in that case; I noticed that when renaming, all the files with references get opened and modified; I don't see the equivalent of this happening in Vim.

Note that I am new to metals.

**To Reproduce**
1. Open a scala project in vim.
2. Open a file with a public class that is references elsewhere in the codebase.
3. Move the cursor on the class name, and use the rename action; in my case, I am pressing `<Space> c` to bring up all the commands, and choose the  `document.renameCurrentWord` command. 
4. Go to insert mode and edit the class name. If the class is also references in the current file, note that the references get updated automatically.
5. Compile the project, and notice that it doesn't compile because the references in other files weren't updated.

Note that the reason why I am bringing up the list of commands above is that the direct keybinding for the rename doesn't seem work for me:
```vimscript
" Remap for rename current word
nmap <leader>rn <Plug>(coc-rename)
```

When I press `<Space> rn`, then it's as if it wasn't recognized at all (and the `rn` command replaces the character under the cursor with n). Most other keybindings involving space work, though.

**Expected behavior**
When renaming a public symbol, all references in all files should be updated, and not just the ones in the current file. I'd like this to work in vim as well, and not just in Visual Studio Code.

**Installation:**
- Operating system: Arch Linux
- Editor: NVIM v0.4.3
- Metals version: v0.8.4

I followed the [vim installation guide](https://scalameta.org/metals/docs/editors/vim.html). I am using the `coc.nvim` plugin, and used the suggested configuration as is.

**Comment by zsolt-donca** [comment]
Hi @ckipp01 , and thank you for your prompt response!

You are of course right. I did not have the `<leader>` key set. Doing the rename by `\rn` does indeed rename a method or a field in all occurrences, across all files. I though that I had the leader key configured other keybinding such as `<space>a` worked - that but those are explicitly using `<space>` and not `<leader>`.

However, I get a weird behavior when renaming a class with the same name as the `.scala` file. Let's say that I rename a class from `Foo` to `Bar`. It happens as follows:
1. I have my cursor over `Foo`, and I hit `\rn`.
2. At the bottom of the screen, I get prompted for the new name, and I enter `Bar` and hit enter, and I use `:wa` to save all changed, as prompted.
3. At this moment, my editor has open `Bar.scala`, but the contents are still the same, declaring the class with the old `Foo` name.
4. If I check the file system, I can see that the old file `Foo.scala` has weird contents:
```
a

Bar
```

What could be going on?

**Comment by ckipp01** [comment]
Hi @zsolt-donca that is a bit odd. I am actually seeing some odd behavior as well trying that exact thing. Let me dig in a bit and see what's going on.

**Comment by ckipp01** [comment]
So my first thought is that this is where the issue lies.
When Metals sends the `textDocument/Rename`, it looks like this:
```json
textDocument/rename

{
  "documentChanges": [
    {
      "textDocument": {
        "version": null,
        "uri": "file:///Users/ckipp/Documents/scala-workspace/test-project/example/src/Test.scala"
      },
      "edits": [
        {
          "range": {
            "start": {
              "line": 2,
              "character": 7
            },
            "end": {
              "line": 2,
              "character": 11
            }
          },
          "newText": "Hi"
        }
      ]
    },
    {
      "oldUri": "file:///Users/ckipp/Documents/scala-workspace/test-project/example/src/Test.scala",
      "newUri": "file:///Users/ckipp/Documents/scala-workspace/test-project/example/src/Hi.scala",
      "kind": "rename"
    }
  ]
} 
```
It would seem that the ordering isn't being followed potentially, and then the second item in the `documentChanges` array is actually happening first, and then the `newText` is being entered into a file that doesn't exist anymore. In this case, `Hi` would be there by itself. This may be an issue with how `coc.nvim` is handling the `documentChanges`, so I'll reach out to them there.

**Comment by ckipp01** [comment]
Hey @zsolt-donca thanks again for finding this. If you follow the conversation [here](https://github.com/neoclide/coc.nvim/issues/1767#issuecomment-614596710) you'll see that the issue was resolved. To see it reflected right away, you'll need to make sure you're using the latest master of coc.nvim or wait until the next stable release.
