### ISSUE TITLE
Feature request: Add ability to disable language server autoloading

### ISSUE THREAD

**Issue by arbitrary-dev** [scalameta/coc-metals#165]
Related to https://github.com/neoclide/coc.nvim/issues/1759

### Is your feature request related to a problem? Please describe.

I'm always frustrated when configured language server loads, I'd like to have more control and start services explicitly when I need them.

### Describe the solution you'd like

An enable flag support for metals language server:
```
"metals.enable": false,
```

### Describe alternatives you've considered

```
:CocUninstall coc-metals
```

**Comment by ckipp01** [comment]
Hey @arbitrary-dev, you'll see this reflected in master, which you're able to use right away. If not, you may have to wait a bit for a new stable release as I'm looking to add a few more things in before the next stable.

Cheers

**Comment by arbitrary-dev** [comment]
Would be nice to have a way to enable it manually, for example:
```
:CocCommand metals.start
```

**Comment by ckipp01** [comment]
Hi @arbitrary-dev hmm, that's maybe a good point, but to be honest I don't want to put any more attention on this setting. It's defaulted to on and I'm assuming the vast majority of users wont' use it. I'd be open to a pr to add a command maybe, but it's currently not a priority for me.
