### ISSUE TITLE
Improve the TVP Panel

### ISSUE THREAD

**Issue by ckipp01** [scalameta/coc-metals#170]
**Decision**

I'm not going to migrate. Ultimately Vista serves a different purpose as a symbol explorer for the current document. It does look quite nice imo, and I'm going to try to spruce up the TVP panel to be a bit more polished.

**Question**

We currently have a built-in version of the [Tree View Protocol](https://scalameta.org/metals/docs/editors/tree-view-protocol.html). This works well enough, but it's definitely not polished. There are also some issues when working with other plugins like NerdTree. See #169 as an example. There have been some talks about one being built-in to [coc.nvim](https://github.com/neoclide/coc.nvim/issues/1649) to support call hierarchies, but [vista](https://github.com/liuchengxu/vista.vim) exists and works wonderfully.

I think some initial work should go into exploring how doable it would be to just replace the TVP module in coc-metals and delegate all of the TVP related stuff to Vista if it's doable. This may result in a much more polished experience.

My goal of this is to _hopefully_ get some feedback from users and take some notes about things I notice as I explore this.

**Screenshots**

<img width="1677" alt="Screenshot 2020-04-18 at 11 26 06" src="https://user-images.githubusercontent.com/13974112/79633944-e6156d80-8167-11ea-87a0-c299b64f0e97.png">

**Things to consider**

 - The image above shows this without custom integration at all, it's just using the built-in coc symbol explorer for the current file. We'd need to figure out how this might work for an entire tree view of not just the current file, but the entire tree.

- In the current panel there are a few things like `ongoing compilations` and some commands like `Cascade compile` etc. Are these features used at all by `coc-metals` users?

- Can Vista allow you to explore external dependencies?

**Things I like**

- As the image shows up, just in general, it's much more polished.

- Currently with the built-in TVP, you can see symbols in a `build.sbt` file for example. Without any work, this works great with Vista.

<img width="1071" alt="Screenshot 2020-04-18 at 11 45 29" src="https://user-images.githubusercontent.com/13974112/79634384-54f3c600-816a-11ea-9f63-477e82f059dc.png">

- I like that you're able to get a preview of the symbol in the sidebar

<img width="983" alt="Screenshot 2020-04-18 at 12 17 25" src="https://user-images.githubusercontent.com/13974112/79635038-a9994000-816e-11ea-8612-c740017f6a5b.png">

**Blockers**

The biggest blocker is that it doesn't fully implement the [Tree View Protocol](https://scalameta.org/metals/docs/editors/tree-view-protocol.html) since it's not meant to. if we did switch to this we'd be missing a huge amount of features that I don't think we can give up. The route that I'm leaning now is to significantly improve the appearance of the TVP panel to mimic the way Vista looks.

**Search terms**

TVP, Vista

**Comment by svalaskevicius** [comment]
looks very nice! and reusing existing components is frequently better than building own :)

I'll try to give my thoughts on the above considerations from a perspective of a (very) new user:

>  The image above shows this without custom integration at all, it's just using the built-in coc symbol explorer for the current file. We'd need to figure out how this might work for an entire tree view of not just the current file, but the entire tree.

~that would be nice, does it support recursive search / filter of the tree?~

 > In the current panel there are a few things like ongoing compilations and some commands like Cascade compile etc. Are these features used at all by coc-metals users?

I saw that they exist but haven't used them.. I normally run `bloop test -w xxx` on another terminal anyways, so not a feature that I'd miss

 > Can Vista allow you to explore external dependencies?

~this would be useful - e.g. in nerd tree I can see only _some_ packages from cats in .bloop/readonly (I expect they only get put there when I open it via coc-metals). and currently, finding a symbol from an included library is extremely difficult - even worse if you only know a function name :) although find symbol vs explore the full tree might be again a different question.~

---

Actually, scratch my answers above :) I'll leave them only as a record of how I came to the thoughts below:

1. I think only looking at symbols from the current file would be enough (at least for me)
2. I would really like to be able to _search_ globally for any symbol (trait, class, object, function, val), and jump to that. not by expanding tree nodes manually, but by searching - e.g. <shift><shift> in intellij. even better if fuzzy search is supported :) kind of fzf for symbols, maybe could also allow namespacing by e.g. packages e.g. `catsfunc` would list Functor from `cats` but not `func` from `com.example.func`
3. would be amazing if I could browse _packages_ and _files_ from my dependencies - not just those that I've opened in metals, but all - e.g. in library view to select `<cats-core>`, then go to the syntax package, and see all subdirectories and files - I don't think lower level is needed - as it would be too much to browse.. 

---

The above is just thoughts for now - was typing as they came :) so more thinking is needed. 

and also, coc-metals is already very nice - keep up the good work :)

**Comment by ckipp01** [comment]
Thanks a bunch for you input @svalaskevicius. I'll address a couple of the points you mentioned.

2. So while this may not be globally in the external library sense, but have you used the symbol search yet? You can do `<space> a` and search for symbols globally in your project.

Here is an image of me searching for `TextEdit` in the Metals code base.

<img width="879" alt="Screenshot 2020-04-19 at 16 35 57" src="https://user-images.githubusercontent.com/13974112/79690672-e68f3080-825b-11ea-860d-3fb5c445c975.png">

If you haven't used it, it works quite well.

3. You can do that currently, even with Java sources. For example if you do a `goto-definition` in one of the things in `cats-core`, it should bring you into where that is defined. From there, you can do a `<space> tf` if you're using the default mappings, and it will bring you in the TVP panel to where that symbol is defined. You can then explore the api of `cats-core` right there. _However_ reading closely I know am reading that that's not what you want 😆 but rather a file/package view. I get that. 

Either way, thanks for you input and patience while I figure some of this stuff out. I keep going back and forth. If nothing else, I think this will definitely cause the TVP stuff to be improved because I'd like to steal some of the stuff from Vista if we don't migrate to it.

**Comment by svalaskevicius** [comment]
Hi. Re 2. Yes, I've used it and it seems very good :) but I couldn't get it to find defs, just classes it seems - or did I miss anything? 

Re 3. Yep. The use case here is when I don't know what I'm looking for, so just browsing and exploring the packages of a library I've included.

**Comment by svalaskevicius** [comment]
Also re 3. If there was such a feature - it would be good to be able to jump to the tree position of the current open file - the usecase is that I got to the file by say go to def, but would like to see what's around it :)

**Comment by landerlo** [comment]
Could you elaborate a bit more about what do you miss in Vista regarding TVP's requirements? It seems to me that creating a new 'metals' Vista executive that reuses the existing lsp executive and adds the required extra nodes for tvp compilation is worth exploring. I can have a quick look but it would help to know the rationale for not going the vista way.

**Comment by ckipp01** [comment]
Hi @landerlo, sure! So the biggest reason I didn't jump on vista is that it's just a simple explorer for the current document. I'd all for having as you said a vista executive that is able to implements the [Tree View Protocol](https://scalameta.org/metals/docs/editors/tree-view-protocol.html), but I assume it's not a small task. Therefore the choice mainly was knowing the time I have to dedicate to this, improving the current TVP panel which is already working is more feasible than the alternative.

With that being said, if this is something you're interested in looking into, I'm be more than happy to give input and help where I can.

**Comment by landerlo** [comment]
> Hi @landerlo, sure! So the biggest reason I didn't jump on vista is that it's just a simple explorer for the current document. I'd all for having as you said a vista executive that is able to implements the [Tree View Protocol](https://scalameta.org/metals/docs/editors/tree-view-protocol.html), but I assume it's not a small task. Therefore the choice mainly was knowing the time I have to dedicate to this, improving the current TVP panel which is already working is more feasible than the alternative.
> 
> With that being said, if this is something you're interested in looking into, I'm be more than happy to give input and help where I can.

I did try to use Vista about a year ago to pass lsp info and it was having trouble with the required tree structures but I see that it's improved a lot in that respect, so I was considering that it might not be much work to add  the extra nodes with the other information reusing the existing lsp functions in a new executive. I'll have a stab at it if I have time. That said, your coc-metals panel is already great, it doesn't need much and for most of us it'll be much more easier to do some work on TypeScript or Lua native (focusing on Neovim could be an option if the native LSP really picks up) than vimscript.

**Comment by ckipp01** [comment]
> I did try to use Vista about a year ago to pass lsp info and it was having trouble with the required tree structures but I see that it's improved a lot in that respect, so I was considering that it might not be much work to add the extra nodes with the other information reusing the existing lsp functions in a new executive. I'll have a stab at it if I have time. That said, your coc-metals panel is already great, it doesn't need much and for most of us it'll be much easier to do some work on TypeScript or Lua native (focusing on Neovim could be an option if the native LSP really picks up) than vimscript.

Thanks for the kind words, and also you hit on something else that was also on my mind. I personally do see the native LSP support in nvim picking up, and personally have been putting some effort in that direction as well. Check out [nvim-metals](https://github.com/ckipp01/nvim-metals) as an example. My idea there is to do as little as possible internally, and simply utilize all the other existing great plugins. I think in that situation it would be extremely ideal retrofit and use Vista as a symbol explorer and potential tree view explorer as well.

**Comment by ckipp01** [comment]
I'm going to go ahead and close this. I really appreciate the input.

Recently there has been some changes to the TVP upstream, which currently break the implementation we have in the compilations window. I'm going to close this ticket in favor of creating a couple separate tickets with explicit things that will now need to be improved.
