### ISSUE TITLE
bloopInstall runs every time, always prompted about Scala version even after choosing Don't Ask Again

### ISSUE THREAD

**Issue by gnfisher** [scalameta/coc-metals#180]
**Question**

1. Every time I open neovim in our project, it imports build and runs bloopInstall again. We do not use sbt-bloop in our project.

2. Every time I open neovim, it always reminds me about the Scala version being older. If I choose Don't ask again, it doesn't remember the next time.

I updated recently, I feel like I may have something misconfigured since that upgrade that coc-metals isn't able to see the last build, my "dont ask again" preferences, and  so on. Looking through google and the docs, I haven't found what it might be. Or perhaps this is normal.

**Comment by ckipp01** [comment]
Thanks for the questions @gnfisher!

1. This is expected if you have an `sbt` project and you're using `coc-metals` metals will detect that you are in an `sbt` project and it embeds a `projects/metals.sbt` file which includes sbt-bloop. Again, this is expected as sbt-bloop is needed to get your build definition from sbt in order for bloop to compile it.
2. So I just tried this with a new project using 2.12.9. I did get the warning, I selected **don't ask again**, closed nvim, opened it again, and even after manually importing again, I wasn't able to get prompted again. So this for sure isn't normal. As long as the `.metals` directory exists in that project, your "decision" is kept. We actually have the opposite problem where they is no way to get the prompt back unless you delete that directory currently.

**Comment by gnfisher** [comment]
Ah, interesting! I created a `.metals` directory and the expected behavior works. Should coc-metals have created that directory on my behalf? 

Thanks so much for the detailed response.

**Comment by ckipp01** [comment]
Yea, it for sure should have created it. Every time metals starts in a workspace one should be created. If possible, remove it, and try opening in that same workspace. One should be created. If not, that's a different issue we should try to troubleshoot.

**Comment by gnfisher** [comment]
So, I was wrong. Even with the `.metals` directory I have the same issues.

I removed coc-metals. I range `PlugClean` and reinstalled. It is now creating the `.metals` directory itself, but I still get prompted.

I also noticed that it tries to update to metals 0.8.4 every time I open neovim and when installing coc-metals, I saw something about a yarn pkg lock conflict with 0.8.1. But it ended up installing properly and does work as expected after it runs `bloopInstall`, reindexes, etc.

**Comment by ckipp01** [comment]
@gnfisher are you able to give me the following:

- Your OS
- Version of Metals
- Version of Vim Or NVIM
- Version of coc.nvim
- Version of coc-metals

**Comment by gnfisher** [comment]
vim version: NVIM v0.4.3
node version: v12.6.0
coc.nvim version: 0.0.78-6e3ecc04cf
term: iTerm.app
platform: darwin
metals: 0.8.4

Not sure where to get coc-metals version, but i just reinstalled with CocInstall coc-metals after PlugClean, PlugUpdate, and CocRebuild.

I noticed in my `CocInfo` output this error: 

```
[info] Loading global plugins from /Users/greg/.sbt/1.0/plugins
unexpected error during source scanning
java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /home
```

as well as this:

```
[error] Not a valid command: metalsEnable
[error] Not a valid project ID: metalsEnable
[error] Expected ':'
[error] Not a valid key: metalsEnable
[error] metalsEnable
[error]             ^
build tool exit: 1
```

**Comment by gnfisher** [comment]
When I reopen nvim in the project having already imported the build and not changed anything, I find this in `CocInfo`:

```
logging to file /Users/greg/Code/thoughtbot/ads-quoting-server/.metals/metals.log
time: initialize in 0.27s
resetting database: /Users/greg/Code/thoughtbot/ads-quoting-server/.metals/metals.h2.db
Flyway upgrade recommended: H2 1.4.200 is newer than this version of Flyway and support has not been tested.
Flyway upgrade recommended: H2 1.4.200 is newer than this version of Flyway and support has not been tested.
Migration of schema "PUBLIC" to version 3 - Jar symbols failed! Please restore backups and roll back database and code!
org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: 
Migration V3__Jar_symbols.sql failed
------------------------------------
SQL State  : 42001
Error Code : 42001
Message    : Syntax error in SQL statement "                                                                      
CREATE TABLE INDEXED_JAR(
  ID INT AUTO_INCREMENT,
  MD5 VARCHAR PRIMARY KEY,
)[*]"; expected "identifier"; SQL statement:
-- Indexed jars, the MD5 digest of path, modified time and size as key
create table indexed_jar(
  id int auto_increment,
  md5 varchar primary key,
) [42001-197]
Location   : db/migration/V3__Jar_symbols.sql (/Users/greg/Code/thoughtbot/ads-quoting-server/file:/Users/greg/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scalameta/metals_2.12/0.7.6/metals_2.12-0.7.6.jar!/db/migration/V3__Jar_symbols.sql)
Line       : 1
Statement  : -- Indexed jars, the MD5 digest of path, modified time and size as key
create table indexed_jar(
  id int auto_increment,
  md5 varchar primary key,
)
```

**Comment by ckipp01** [comment]
Thanks for the info @gnfisher. I'm a bit perplexed by some of these.

First of all, the reference to `metalsEnable` shouldn't be there as that was removed quite a long time 🤔 . The same with the h2 error that you're seeing, we actually changed that a bit as well, and it's referencing the old schema. Everything seems to point that you're using a metals that is pre 0.8.0.

Is there a chance that you used metals before where you use to have to bootstrap your own? I know in the past others had issues where they left the `languageServer` key in their `:CocConfig` referencing the old metals while also installing `coc-metals`. All sorts of stuff can go wrong when that happens.

Also, when you open up your project, can you send me everything you are seeing in your `.metals/metals.log` file?

**Comment by gnfisher** [comment]
I did have the languageserver things in my CocConfig from an older version. I removed it, cleaned everything, blew away .bloop and .metals directories, and installed fresh.

Now, I am getting No Semantic DB errors, which I've seen in the past and resolved by blowing away .bloop and .metals. No luck this time. I can't jump to definiton, etc. at the moment.

Here is the log

```
INFO  started: Metals version 0.8.4 in workspace '/Users/greg/Code/thoughtbot/ads-quoting-server'
INFO  time: initialize in 0.24s
WARN  no build target for: /Users/greg/Code/thoughtbot/ads-quoting-server/src/main/scala/ads/quoting/Main.scala
INFO  running '/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -jar /var/folders/78/ljm69hgd29v7wx9s550k_8c00000gn/T/metals3965291461552580813/sbt-launch.jar -Dbloop.export-jar-classifiers=sources bloopInstall'
INFO  [info] Loading global plugins from /Users/greg/.sbt/1.0/plugins
INFO  [info] Loading settings for project ads-quoting-server-build from plugins.sbt,metals.sbt ...
INFO  [info] Loading project definition from /Users/greg/Code/thoughtbot/ads-quoting-server/project
INFO  [info] Loading settings for project ads-quoting-server from build.sbt ...
INFO  [info] Set current project to ads-quoting-server (in build file:/Users/greg/Code/thoughtbot/ads-quoting-server/)
INFO  [info] Configured .env environment
INFO  [success] Generated .bloop/ads-quoting-server.json
INFO  [success] Generated .bloop/ads-quoting-server-test.json
INFO  [success] Total time: 3 s, completed Apr 23, 2020 1:57:12 PM
INFO  build tool exit: 0
INFO  time: ran 'sbt bloopInstall' in 10s
Starting the bsp launcher for bloop...
Opening a bsp server connection with 'bsp --protocol local --socket /var/folders/78/ljm69hgd29v7wx9s550k_8c00000gn/T/bsp-launcher525890444577408796/bsp.socket'...
Waiting for the bsp connection to come up...
[0m[32m[D][0m Loading 2 projects from '/Users/greg/Code/thoughtbot/ads-quoting-server/.bloop'...
[0m[32m[D][0m Loading project from '/Users/greg/Code/thoughtbot/ads-quoting-server/.bloop/ads-quoting-server-test.json'
[0m[32m[D][0m Loading project from '/Users/greg/Code/thoughtbot/ads-quoting-server/.bloop/ads-quoting-server.json'
[0m[32m[D][0m Waiting for a connection at local:///var/folders/78/ljm69hgd29v7wx9s550k_8c00000gn/T/bsp-launcher525890444577408796/bsp.socket...
The server is listening for incoming connections at local:///var/folders/78/ljm69hgd29v7wx9s550k_8c00000gn/T/bsp-launcher525890444577408796/bsp.socket...
Starting thread that pumps stdin and redirects it to the bsp server...
Starting thread that pumps server stdout and redirects it to the client stdout...
INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /Users/greg/Library/Caches/org.scalameta.metals/bsp.trace.json
INFO  time: connected to build server in 0.11s
INFO  Connected to Build server v1.4.0-RC1-144-802d3118
INFO  time: indexed workspace in 4.97s
INFO  compiling ads-quoting-server (252 scala sources)
INFO  time: compiled ads-quoting-server in 56s
ERROR code navigation does not work for the file '/Users/greg/Code/thoughtbot/ads-quoting-server/src/main/scala/ads/quoting/Main.scala' because the SemanticDB file '/Users/greg/Code/thoughtbot/ads-quoting-server/.bloop/ads-quoting-server/bloop-bsp-clients-classes/classes-Metals-IwoVtBFTTS6LV-GQ54_Y8A==/META-INF/semanticdb/src/main/scala/ads/quoting/Main.scala.semanticdb' doesn't exist. There can be many reasons for this error. 
```

**Comment by gnfisher** [comment]
That seems to have been the issue! I removed the languageServer configs from CocConfig, blew away .bloop and .metals directories, and reinstalled. Now I am no longer prompted to re-import the build every time.

Thanks so much for your patience and help!
