### ISSUE TITLE
How to run bloop tests?

### ISSUE THREAD

**Issue by arbitrary-dev** [scalameta/coc-metals#186]
**Question**

Is there a way to run something like `:!bloop test project` from Vim to reuse already compiled classes?

**Installation:**

- Operating system: Linux
- Vim version: 8.1.1486
- coc.nvim version: 0.0.77-817efd5108
- coc-metals extension version: 0.8.0
- Metals version: 0.8.4+62-67ef4e74-SNAPSHOT

**Search terms**

bloop test

**Comment by ckipp01** [comment]
@arbitrary-dev You could use the built in `:terminal` and then issue that `bloop test project` command to test. Or just switch to the terminal and do the command there. There is currently no built-in functionality for this at the moment.

**Comment by arbitrary-dev** [comment]
But it seems to be using different  bloop session and recompiles classes already compiled by coc-nvim session.

**Comment by ckipp01** [comment]
hmm, it should be recompiling them I believe. Bloop cli is just seen as another "client" in this situation, and it should re-use the compilation. If it's not, you may want to reach out on the bloop channels to confirm this.
