### ISSUE TITLE
Installation under FreeBSD

### ISSUE THREAD

**Issue by jan0sch** [scalameta/coc-metals#204]
The plugin does not install under FreeBSD.

**Steps to reproduce the behavior:**

Either use `:CocInstall coc-metals` or the Vim-Plug installation and do a `:PlugInstall`.

There are two different errors here but I guess below the hood they might be the same.

**Error message from CocInstall**

There is just a red status line saying:

```text
[coc.nvim] Error on install coc-metals: Error: EPERM: operation not permitted, unlink '/tmp/coc-metals-s4W6ca'
```

**Error message from PlugInstall**

There are some message but they scroll through too fast and in the end the status line says:

```text
[coc-nvim] extension "coc-metals" doesn't contain main file ~/.config/nvim/bundle/coc-metals/lib/index.js.
```

**Expected behavior**

The plugin should install or provide an alternate way to install it which works.

**Installation:**

- Operating system: FreeBSD 12.1
- Vim or nvim version: 0.4.3
- coc.nvim version: latest stable
- coc-metals extension version: latest stable
- Metals version: 0.9.0

**Notes**

This happened today as I was updating my plugins and metals. Until now I used only coc.nvim without the coc-metals script (using the coursier bootstrap installation which seems to be gone from documentation now). I wouldn't mind the plugin but as it seems it doesn't work without it anymore. :-(

Running something like `CocRequestAsync('metals', 'workspace/executeCommand', { 'command': 'build-import' })` manually yields in an error message `Language server metals not found'

**Comment by ckipp01** [comment]
Hey, thanks for reporting this.

Yea, from looking it, the install is for sure failing based off your messages. However, I don't think this is unique to `coc-metals`. Looking at the issues on [coc.nvim](https://github.com/neoclide/coc.nvim/issues/1483) there seems to be an open one about installation on BSD. However, according to [this](https://github.com/neoclide/coc.nvim/issues/1483#issuecomment-585590159) is seems that you should be able to just go to that directory and do a `yarn add coc-metals`, which should then install it correctly. Are you able to give that a try?

**Comment by jan0sch** [comment]
The workaround did not work on first try and errored out with 
```
error An unexpected error occurred: "ENOTDIR: not a directory, lstat '~/.config/coc/extensions/node_modules/coc-metals/.prettierignore'".
```

However, after deleting `~/.config/coc` and `~/.config/nvim/bundle` and re-installation of neovim plugins I was able to perform it without errors (the workaround).

```text
% cd ~/.config/coc/extensions
% yarn add coc-metals
...
Done in 2.27s.
```

So far it seems to work. Thanks for your help. :heart:

**Comment by ckipp01** [comment]
Great. Glad you were able to get it to work 👍
