### ISSUE TITLE
TreeView opens when typing "-" in netrw

### ISSUE THREAD

**Issue by greenhat** [scalameta/coc-metals#206]
**Describe the bug**

TreeView opens when typing "-" in netrw. Not every time, around 50% of cases. FWIW I don't have NerdTree plugin installed.

**To Reproduce** Steps to reproduce the behavior:

1. Open netrw.
2. Type "-".
4. See TreeView windows(3) open.

**Expected behavior**

Not to open TreeView.

**Installation:**

- Operating system: macOS
- Vim or nvim version: 0.4.6
- coc.nvim version: 0.0.78-d6dd56bba8
- coc-metals extension version: 0.8.3
- Metals version: 0.9.0

**Comment by ckipp01** [comment]
Thanks for reporting @greenhat. That's very odd behavior. 🤔 

I'm trying to reproduce this, and I'm unable to. I have no idea how the TVP panel would open without a `CocCommand metals.tvp` being executed, and I'm assuming that you don't have `-` rebound to anything right?

**Comment by greenhat** [comment]
@ckipp01 Thanks for the quick replay! No, I don't have `-` rebound. I understand that its hard to reproduce and probably its my local conf problem.  

FWIW, here is my tvp bindings:
```
" Toggle panel with Tree Views
nnoremap <silent> <leader>v :<C-u>CocCommand metals.tvp<CR>
" Toggle Tree View 'metalsBuild'
nnoremap <silent> <leader>vb :<C-u>CocCommand metals.tvp metalsBuild<CR>
" Toggle Tree View 'metalsCompile'
nnoremap <silent> <leader>vc :<C-u>CocCommand metals.tvp metalsCompile<CR>
" Reveal current current class (trait or object) in Tree View 'metalsBuild'
nnoremap <silent> <leader>vf :<C-u>CocCommand metals.revealInTreeView metalsBuild<CR>
```
Space is the `<leader>`.

**Comment by ckipp01** [comment]
Hi @greenhat, I played around a bit more with this tonight and I've still been unable to get this to happen :/

If you are able to lock down it happening consistently that would be super helpful to try and track down what's happening. I'll leave this open for a while just in case someone else happens to be having the same issue.

**Comment by greenhat** [comment]
@ckipp01 Thank you for your efforts! I'll keep looking for the cause.

**Comment by ckipp01** [comment]
I'm going to go ahead and close this @greenhat. I haven't seen it pop up at all yet. Again, if you're able to reproduce this consistently, please do comment back in here.
