### ISSUE TITLE
Not able to run/debug via vimspector and code lens

### ISSUE THREAD

**Issue by vito-c** [scalameta/coc-metals#235]
I am using the sample project here: https://github.com/ckipp01/metals-minimal-sbt
With mac os x catalina 10.15.5 and neovim 0.4.3

I'm online `4` of the Hello.scala file and I typ <leader>cl and it asks me  if I want to run or debug . I tried both options separately.

The files: dap-server.trace.json and dap-client.trace.json are both empty of data.

Maybe I could try setting a different port for the debugger to connect to?

Thanks!

**Comment by ckipp01** [comment]
Can you also provide the version of coc.nvim, metals, and coc-metals.

Also, can you include your vimspector configuration file?

**Comment by vito-c** [comment]
coc-metals: `844c5ef`
coc.nvim: `aa36478`
Metals version: `0.9.0`
bloop: `1.4.0-RC1-229-b7c15aa9`


./vimspector/configurations/macos/scala/coc-metals.json 
```json
{
  "configurations": {
    "coc-metals": {
      "adapter": {
        "port": "${port}",
        "variables": {
        }
      },
      "configuration": {
        "request": "launch"
      },
      "breakpoints": {
        "exception": {
          "caught": "N",
          "uncaught": "N"
        }
      }
    }
  }
}
```
Note: there is nothing in my gadgets directory for scala.


coc-settings.json (just in case)
```json
{
  "coc.preferences.messageLevel": "error",
  "metals.javaHome": "/Library/Java/JavaVirtualMachines/jdk1.8.0_231.jdk/Contents/Home",
  "coc.preferences.formatOnType": true,
  "codeLens.enable": true,
  "diagnostic.errorSign": "✘",
  "diagnostic.warningSign": "⚠ ",
  "metals.statusBarEnabled": true,
  "suggest.autoTrigger": "always",
  "languageserver": {
    "golang": {
      "command": "gopls",
      "rootPatterns": ["go.mod"],
      "filetypes": ["go"]
    }
  }
}
```

**Comment by ckipp01** [comment]
Hmm, I'm also actually having some issues locally with having the global configuration. I need to chase down what is going on. In the meantime, if you put a `.vimspector.json` file with those same settings in your project root, and then try again, does it work?

**Comment by ckipp01** [comment]
Ah, actually, your path that you have listed `./vimspector/configurations/macos/scala/coc-metals.json`. I believe this wrong, unless `./vimspector` is where the plugin lives, but I'm assuming not. For example I install it with Vim Plug, so for me it's `~/.vim/plugged/vimspector/configurations/macos/scala/coc-metals.json`.

**Comment by vito-c** [comment]
`~/.config/nvim/bundle/vimspector/configurations/macos/scala/coc-metals.json`

bundle is where all of my plugins live and nvim is a symlink to my `~/code/configs/pirate-vim`

**Comment by ckipp01** [comment]
Alright gotcha. And did you try with the `.vimspector.json` file at the root of your project?

**Comment by vito-c** [comment]
so `cp ~/.config/nvim/bundle/vimspector/configurations/macos/scala/coc-metals.json <project-root>/.vimspector.json` ?

**Comment by ckipp01** [comment]
Hmm, so I'm having a hard time chasing this down. Even copying your coc config, and your coc-metals.json file, I'm able to get it to work fine on the example project. So with the sample project with the `<root-directory>/.vimpsector.json` when you choose even `run`, just nothing happens?

**Comment by pedrohjordao** [comment]
I'm also having issues with this
but for me code lenses do not show up, with local .viminspector.json or global configuration
coc is correctly configured because i can use code lenses with other language plugins

**Comment by ckipp01** [comment]
@vito-c if you have some time, can you create a [`bsp.trace.json`](https://scalameta.org/metals/docs/contributors/getting-started.html#workspace-logs) file like described in the docs and show me what you get when you attempt to trigger a debug?

@pedrohjordao I'll basically need some info before I can help at all. Like I mentioned above, I'll need to know your version of Metals, coc-metal, coc.nvim, vimspector. What does your `:CocConfig` look like, are you using Vim or Nvim, etc. Also if you can provide the trace file I mentioned up above to @vito-c that'd be helpful.

**Comment by pedrohjordao** [comment]
Gladly


NeoVim info

```
$ nvim --version
NVIM v0.5.0-nightly-6-gef0398f
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/root/parts/nvim/build/build/config -I/root/parts/nvim/build/src -I/root/parts/nvim/build/.deps/usr/include -I/usr/include -I/root/parts/nvim/build/build/src/nvim/auto -I/root/parts/nvim/build/build/include
Compiled by root@snapcraft-nvim

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

```

CocConfig:
```
{
  "coc.preferences.formatOnSaveFiletypes": ["scala", "rust"],
  "coc.preferences.formatOnType": true,
  "codeLens.enable": true,
  "suggest.autoTrigger": "always",
  "languageserver": { "kotlin": { "command": "~/Projects/kotlin-language-server/server/build/install/server/bin/kotlin-language-server", "filetypes": ["kotlin"] } } 
}
```

Currently i've setup the .vimspector.json file in the root of the project with the same content as described in the readme.

To make things easier I'm using the same sample project as OP

Log: 
[bsp.trace.json.log](https://github.com/scalameta/coc-metals/files/4872718/bsp.trace.json.log)

Not sure how to extract the version of the plugins (using Plug-vim) but i'm running the lastest master versions of all plugins.

**Comment by ckipp01** [comment]
Thanks for sending @pedrohjordao. So you just don't have any code lenses at all showing up correct? You don't see them for the main method, but are you seeing them for the when methods are being overridden? In that example project you mentioned, I just updated an added another file `OtherGreeting.scala`. In there I override `greeting`. On the line you should see the ` ‣  greeting` at the end of the line with the override on it. Do you see that code lens? And while you do this, could you do the same thing you did for the `bsp.trace.json` file but do it for the `lsp.trace.json` file. First things first, let's figure out why you're not seeing code lenses.

**Comment by pedrohjordao** [comment]
yup, did the same and the code lens for the override show up.

the produced trace: [lsp.trace.json](https://github.com/scalameta/coc-metals/files/4875151/lsp.trace.json.log)

**Comment by ckipp01** [comment]
So the issue @pedrohjordao is that `debuggingProvider` is not being set in you `initializationOptions`. The check for this happens here:
https://github.com/scalameta/coc-metals/blob/1a265355fe97e2d8524a9e9cbd8e1ccf66d41031/src/index.ts#L194-L196

I can see that you're using nvim, but do you have vimspector correctly installed?

Without having `debuggingProvider` set to true in `initializationOptions` there is no way for the debug/run code lenses to get sent to the client.

**Comment by vito-c** [comment]
I eventually got mine to work but it was somewhat magical.

I  recommend the following:
1. clone this as use this project as  your test bed: https://github.com/ckipp01/metals-minimal-sbt
2. make sure vimspector configs are in the project root directory 
3. make sure all the debugging files are setup
4. try it out with your default vimsettings
5. try it with VSCode to validate it works and isn't something else on your system
6. now it's time to debug your configuration  make a minimal vimrc that sources your plugins. I would try first with only the relevant plugins coc, coc-metals, your leader/color scheme, etc. keep it very basic
7. If that works then add all of your plugins. Then if it doesn't work after adding all of your plugins use a binary search to remove plugins to see if you can find the culprit.
8. If it works with all of your plugins then start adding things from your vimrc. I would be cautious  about autocmds as those are probably the culprit.

Hopefully this helps :)

**Comment by pedrohjordao** [comment]
I hadn't setup the gadgets it seems... but even after doing that nothing shows up

But yeah this is looking like a vimspector issue, tried to run their tests and it can't make it work either

**Comment by vito-c** [comment]
Java uses YCM. I suggest you try setting it up using VSCode so  you know it works with metals. Then try with a very minimal .vimrc

**Comment by ckipp01** [comment]
> edit: i actually can't read and didn't realize the --all flag didn't set up the adapter for java.

Well you actually shouldn't really have to do anything or install any adapter in order for this to work with coc-metals. After installing vimspector, coc-metals take care of directing the communication to vimspector, and then bloop is your DAP server.

**Comment by pedrohjordao** [comment]
Hum, ok
So, just to make sure I've cleared the vimperator plugin and reinstalled it with no success
Also checked metals plugin in vscode and everything works fine there (run, debug)
When I have some time today I'll make a new clean vimrc as sugested by @vito-c and see if it works

**Comment by pedrohjordao** [comment]
Ok, I think i've solved it
Removed every plugin but coc and vimspector, still having problems
Removed every extension from coc but coc-metals, still having problems
Removed coc-metals and added it back and now it works!

**Comment by vito-c** [comment]
Started happening again for me :(

**Comment by vito-c** [comment]
I also couldn't get VSCode to work for this project
![image](https://user-images.githubusercontent.com/820137/88431363-05e3af80-cdaf-11ea-93e3-1feecbc97c45.png)

**Comment by ckipp01** [comment]
@vito-c to avoid this getting stale, are you still having these issues with run?

**Comment by vito-c** [comment]
Hi @ckipp01 I am not having issues with run right now. I do think sometimes it won't start the inspector and that I've run into a case a few times where vimspector just crashes. I have also run into a case where I want to run debug a second time and things go boom. I don't have clear reproducible steps or even logs at the moment :( So it's fine to close but when I have more time I hope to get a better bug report.
