### ISSUE TITLE
Towards V1

### ISSUE THREAD

**Issue by ckipp01** [scalameta/coc-metals#252]
I believe `coc-metals` to be quite stable at this point and it is implementing pretty much everything Metals has to offer more or less. Due to that, I think it's time that this gets bumped to v1. Howerver, there are a few final things that I'd like to get accomplished before finally marking this as v1.

- Work on getting debugging to seamlessly work for Vim users and Nvim users without virtual text. Vimspector makes this totally doable, but the effort just need to be put in to research, document, and I'm assuming make pretty small changes to `coc-metals`. (#235)
- ~Clean up doctor (#248)~
- Do a quick run through of the documentation again to ensure everything is there and also add a small section with helpful stuff for those that may be new to the entire coc ecosystem.
- ~Make the necessary changes to no longer need to set the client (https://github.com/scalameta/metals/issues/1895)~

~Bonus: It'd be great to have the Japanese translation done for V1, but that's reliant on @tani 😄 no pressure.~

If anyone feels like there should be anything else addressed please let me know!

**Comment by cbcoutinho** [comment]
@ckipp01 SBT 1.4. includes BSP support, no longer requiring coc-metals to install one. Will this be supported in v1?

**Comment by ckipp01** [comment]
Hey @cbcoutinho, that's a good question. You can already use coc-metals with the sbt BSP support pretty much the exact same way that is outlined [here for VS COde](http://eed3si9n.com/sbt-1.4.0). However, it's a good point that I should maybe look at adding a small section about it in the docs.

Apart from that, all of the work that will be needed to smooth out the process will actually be handled in Metals itself. You can see a bit more context about that [here in this discussion](https://github.com/scalameta/metals/issues/2049)

**Comment by jqno** [comment]
I've been using coc-metals as my main way of working with Scala for months now. I've sometimes run into strange stability issues after upgrading (such as #255), but on the whole, I've been a very happy user. I say go for it.

**Comment by ckipp01** [comment]
That's great to hear @jqno. Honestly, I'll probably do this soon. I haven't looked much into some of the remaining things I have listed mainly due to me having fully switched over to https://github.com/scalameta/nvim-metals, so much of my attention has been focused there 😬. I think things like figuring out a better Vimspector integration would be ideal, but I think they can also probably be done after the bump. Thanks for your comment.

**Comment by jqno** [comment]
I'd like to try out Vimspector too, but I don't see that happening for me real soon; I don't miss being able to debug all that much. For me, it doesn't stand in the way of 1.0.

**Comment by ckipp01** [comment]
I figure now is as good as time as any. Seeing that coc-metals is as stable as it is, and also seeing that I don't see any huge changes coming to it, I went ahead and released v1.

Thanks for all the support everyone!
