### ISSUE TITLE
Can I use multiple vim windows using the same metals instance?

### ISSUE THREAD

**Issue by kuberlog** [scalameta/coc-metals#253]
Hi. Is there a way to check if a metals instance is running and to not boot metals if it is?

**Comment by ckipp01** [comment]
Hello! So it sort of sounds like two different questions based off the title and content.

> Can I use multiple vim windows with the same metals

No, you'll need an instance of Metals per workspace.

> Is there a way to check if metals is running and not to boot metals if it is?

Ah, not really? So in this situation you'd want to disconnect from your other project and connect it to your current project?

**Comment by kuberlog** [comment]
I want to open vim, it check to see if metals is open for a particular build.sbt, if it isn't then start metals, if it is then just connect to the metals that is already running (presumably started by another vim instance). I think you are saying that this is not currently available.

**Comment by ckipp01** [comment]
Correct, this is not available. I'd also probably try to avoid this as well. Out of curiosity, in what scenario would you be opening the same project multiple times with Vim instead of just splitting your screen?

**Comment by kuberlog** [comment]
Ok. Thanks for the info. I'll close the issue.

My system already has a good tiling window manager and I think Vim's screen splitting is a violation of the Unix philosophy (do one thing well) and I'd rather not use it. For an example of how this becomes a problem IRL: Imagine I have 2 vim screens and a chromium instance open; I'd have to use 1 set of keybindings to navigate between the screens and another set to navigate from vim into the browser. I just want 1 set of keybindings to navigate across all 3.

**Comment by ckipp01** [comment]
Thanks, I appreciate the explanation.
