### ISSUE TITLE
Weird highlighting in signature window

### ISSUE THREAD

**Issue by lewis6991** [scalameta/coc-metals#309]
**Describe the bug**

Not sure if this is an issue with coc.nvim or not but posting here first.

When the highlight groups `StatusLine` and `Normal` match, the signature window looks ok.

![Screenshot 2020-09-23 at 16 44 24](https://user-images.githubusercontent.com/7904185/94036746-8ed19400-fdbc-11ea-8423-9e2a34b629e8.png)

However when I change the `StatusLine` highlight group so it doesn't match `Normal` I get this:
![Screenshot 2020-09-23 at 16 45 08](https://user-images.githubusercontent.com/7904185/94036756-91cc8480-fdbc-11ea-9873-daa258d6d65c.png)

**To Reproduce** Steps to reproduce the behavior:

Set the highlight groups `StatusLine` and `Normal` foregrounds to be distinct from each other.

Or you can instead use this [vim colorscheme](https://github.com/lewis6991/moonlight.vim) to recreate the issue.

**Installation:**

- Operating system: Linux
- Vim or nvim version: NVIM v0.4.4
- coc.nvim version: 0.0.79-d2a3186309
- coc-metals extension version: 0.9.5
- Metals version: 0.9.4

**Search terms**

signature highlight color StatusLine Normal

**Comment by ckipp01** [comment]
Thanks for the report! So this looks like this: https://github.com/scalameta/coc-metals/wiki/Commonly-Asked-Questions#how-do-i-fix-the-odd-highlighting-in-floating-windows-when-using-neovim. I don't want to admit the amount of time I wrestled with that before the maintainer of my theme helped me out. If you look through closed issues in coc.nvim you'll actually see quite a few references to this and not a lot of helpful responses.

**Comment by lewis6991** [comment]
Thanks for the response. I've hit the issue mentioned in the link before and was able to fix my colorscheme (of setting bg of Normal to None) so I don't think that is the issue.

Honestly the problem looks like the `Normal` highlight group is applied one character too early. Perhaps and index error in the code?

Also FWIW, I don't get this issue when using coc-python so I guessed this was something specific to coc-metals.

![Screenshot 2020-09-24 at 09 12 55](https://user-images.githubusercontent.com/7904185/94119076-4bbc0300-fe46-11ea-9a18-4f10678e9122.png)

**Comment by ckipp01** [comment]
Yea I'm pretty confident in saying that it's 100% not a coc-metals issue. Mainly because the extension doesn't do anything at all with the float info. coc-metals simply receives the response from Metals, and then it's is displayed by coc.nvim in the hover window. There are also other extensions that have hit on this. For example, you can see a conversation about this [here](https://github.com/neoclide/coc.nvim/issues/1248).

**Comment by lewis6991** [comment]
It looks like that specific issue is addressed by the [FAQ](https://github.com/scalameta/coc-metals/wiki/Commonly-Asked-Questions#how-do-i-fix-the-odd-highlighting-in-floating-windows-when-using-neovim) you linked and that the `Normal` highlight should have it's background set to `None` to fix the issue.  The problem here is that `Normal` appears to be applied one character early as opposed to being incorrectly defined.

Thanks for looking into this anyway. If it's not a problem with coc-metals then I can repost this issue on coc.nvim.

**Comment by ckipp01** [comment]
Hey, gotcha. Sorry I misunderstood a bit what you meant at first withe what the actual main issue was. 🤔 as for the one character early, that's really a bit odd. One thing you can do if you as well is to [create an lsp.trace.json](https://scalameta.org/metals/docs/contributors/getting-started.html#json-rpc-trace) and then tail it. When you execute a hover you'll see the exact information that is coming back from the server. That way you can see exactly what is being given to the hover which may help with seeing if anything is odd looking.

**Comment by lewis6991** [comment]
Got this result:

```Result: {
  "signatures": [
    {
      "label": "inlineOne(inliner: Top[TIdent], inlinees: List[TIdent]): Top[TIdent]",
      "documentation": {
        "kind": "markdown",
        "value": ""
      },
      "parameters": [
        {
          "label": "inliner: Top[TIdent]",
          "documentation": {
            "kind": "markdown",
            "value": ""
          }
        },
        {
          "label": "inlinees: List[TIdent]",
          "documentation": {
            "kind": "markdown",
            "value": ""
          }
        }
      ]
    }
  ],
  "activeSignature": 0,
  "activeParameter": 0
}
```

Looks kind of sensible to me? I know very little about LSP, but should the label include the type annotation? Could that be tripping up coc.nvim? I don't have the output for coc-python but the signature doesn't underline the type annotation in the same way which leads me to believe that the label is just the identifier name?

**Comment by ckipp01** [comment]
> Looks kind of sensible to me? I know very little about LSP, but should the label include the type annotation?

Yea, that should actually be fine. You can see a bit about what is all available here in the [spec](https://microsoft.github.io/language-server-protocol/specification). The documentation field there would be what you would expect, documentation about the method etc. So the label does look right, and yes, it should have the type annotation.

> Could that be tripping up coc.nvim?

It really shouldn't be. I've been playing around with this a bit and coc.nvim should handle this just fine:

<img width="562" alt="Screenshot 2020-09-26 at 16 01 38" src="https://user-images.githubusercontent.com/13974112/94342533-e3ba1800-0011-11eb-9d7c-3ed33e6b2b97.png">

> I don't have the output for coc-python but the signature doesn't underline the type annotation in the same way which leads me to believe that the label is just the identifier name?

I don't believe so. The label needs to actually be the full signature since the label of the parameter should be a substring of the label of the containing signature. You can see this in the spec I referenced above:

> * *Note*: a label of type string should be a substring of its containing signature label.

**Comment by lewis6991** [comment]
Before I pass this on to coc.nvim could you see if you can recreate the issue by changing the Normal hl group?

**Comment by ckipp01** [comment]
So when I start messing around with the Normal highlight groups I hit on the same issues as I linked:

<img width="401" alt="Screenshot 2020-09-26 at 18 24 56" src="https://user-images.githubusercontent.com/13974112/94345383-af505700-0025-11eb-9509-9bd6089dea3f.png">

**Comment by lewis6991** [comment]
Thanks for doing that. I'll have to see if I can recreate this in a minimal env. Hopefully the issue is with my colourscheme.

**Comment by ckipp01** [comment]
For sure. Let me know if there is any other way I can help or test anything!

**Comment by lewis6991** [comment]
Ok I've been able to recreate this in a minimal env. Basically the issue can be reproduced if you have a colorscheme with this contents:

```viml
hi clear
syntax reset
let g:colors_name = 'testcolors'

highlight Normal      guifg=#FFFFFF guibg=#000000
highlight NormalFloat guifg=#FF0000 guibg=#00AA00
```
Note: These highlight commands must be invoked in a colorscheme. The issue doesn't appear if the above is run in init.vim.

This gives me:
![Screenshot 2020-09-28 at 11 58 29](https://user-images.githubusercontent.com/7904185/94424650-78dc1e80-0182-11eb-8228-62e8a0cb2eb4.png)

I've also put together a tar to recreate this which you may not need but sharing here anyway: [coc-metals_issue309.tar.gz](https://github.com/scalameta/coc-metals/files/5291762/coc-metals_issue309.tar.gz). Here's a tree of the tar:
```
.
├── build.sbt
├── config
│   └── nvim
│       ├── autoload
│       ├── coc-settings.json
│       ├── init.vim
│       └── pack
│           └── myplugins
│               └── start
│                   └── testcolors
│                       └── colors
│                           └── testcolors.vim
├── main.scala
└── run.sh
```

To run the minimal env simply extract and run `source run.sh` in a bash compatible shell. Then run `nvim <my scala file>` to test.

@ckipp01, would you be able to try and recreate this using the above info?

**Comment by ckipp01** [comment]
Hey, again, I think this belongs in coc.nvim. coc-metals has absolutely no part in the highlighting of the float. 100% of that is handled in coc.nvim. If there is something wrong with what Metals is returning, I'm happy to have a look to see how we can solve this. But again, coc-metals plays literally no part in how this is displayed. Please submit this upstream.

**Comment by lewis6991** [comment]
Sure, I totally understand. Since I can only see this issue with coc-metals, I just wanted for someone else to confirm this before passing this onto devs who aren't fluent with scala tools. Regardless I'll just pass this on. Thanks anyway!

**Comment by ckipp01** [comment]
For sure, that's understandable. On the positive, it shouldn't matter that much about the Scala tools. As long as you can show the actual signatures in the response and the behavior you're seeing, they should be able to help. However, I'm assuming the answer you're going to get is that _your theme needs to handle this_.

**Comment by lewis6991** [comment]
Seen this issue with [nvim-metals](https://github.com/scalameta/nvim-metals) too so it might even be a neovim issue.
