### ISSUE TITLE
Is decoration protocol only available for worksheet ?

### ISSUE THREAD

**Issue by Freyskeyd** [scalameta/coc-metals#345]
**Question**

Hello !

I'm testing coc-metals for some days but I didn't see any decoration around my code (like defined in the decoration protocol).

I was wondering if it was only available in `*.worksheet.sc` file ?
If not, maybe the documentation is missing some element to configure it, I freshly installed coc anc coc-metals but it appears to not appear (eheh).

**Installation:**

- Operating system: macOS
- Vim or nvim version: nvim 0.4.4
- coc.nvim version: master (release)
- coc-metals extension version: master
- Metals version: 0.9.5+16-83a9e341-SNAPSHOT

**Comment by ckipp01** [comment]
Thanks for the question @Freyskeyd! The decoration protocol is actually only used for a couple things within Metals, mainly worksheet decorations and implicits/inferred types. As you discovered, the worksheets work, but for the implicits/inferred types, there is actually another setting that an editor needs to support to show them, inline decorations. Nvim doesn't yet allow for decorations to be placed within a line, only after. So instead, we show them in the hover when you have `showInferredType` and `showImplicitArguments` enabled.

Where there any other use cases specifically you were curious about?

**Comment by Freyskeyd** [comment]
Oh ok!

I will try those options, I will thinking about the coc rust analyzer behaviour and though it was the same things.

Here's the Rust decoration:

![Capture d’écran 2020-11-12 à 09 28 51](https://user-images.githubusercontent.com/1394604/98915050-b0e8b800-24c9-11eb-9e04-076d649c6bc4.png)

**Comment by ckipp01** [comment]
> Here's the Rust decoration

Gotcha, yea the decorations that Metals has are actually quite similar to this, but also in the middle of lines as well.

**Comment by Freyskeyd** [comment]
mmh after testing the `worksheet` method, I dont see any decoration.
I added the previously mentioned options but it does'nt appear either.

**Comment by ckipp01** [comment]
> mmh after testing the worksheet method, I dont see any decoration.

So your worksheets aren't working at all?

> I added the previously mentioned options but it does'nt appear either.

Keep in mind these options for coc-metals show the extra synthetic information in the hover, not as virtual text.

https://scalameta.org/metals/blog/2020/11/10/lithium.html#show-implicits-and-type-decorations
