### ISSUE TITLE
*.sbt files not supported 

### ISSUE THREAD

**Issue by nicobao** [scalameta/coc-metals#361]
**Describe the bug**

On opening a Scala project with the coc extension, .scala files are supported correctly (auto-completion, hover..etc all works).
But support *.sbt files, such as build.sbt, does not work.

**To Reproduce** Steps to reproduce the behavior:

1. Open the file https://github.com/scalameta/metals/blob/main/build.sbt  with neovim
2. Wait for Metals to successfully start and "indexing complete!" appear
3. Notice that you have no hover/autocompletion/go-to-defintion

:CocCommand.workspace.showOutput content:
```
2020.12.06 23:50:55 INFO  logging to file /home/nicolas/third-parties/metals/.metals/metals.log
2020.12.06 23:50:55 INFO  Started: Metals version 0.9.7 in workspace '/home/nicolas/third-parties/metals' .
2020.12.06 23:50:57 INFO  time: initialize in 2.31s
2020.12.06 23:50:58 INFO  Attempting to connect to the build server...
2020.12.06 23:50:59 INFO  skipping build import with status 'Installed'
2020.12.06 23:50:59 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/nicolas/.cache/metals/bsp.trace.json
2020.12.06 23:50:59 INFO  Attempting to connect to the build server...
2020.12.06 23:50:59 INFO  Attempting to connect to the build server...
2020.12.06 23:50:59 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/nicolas/.cache/metals/bsp.trace.json
2020.12.06 23:50:59 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/nicolas/.cache/metals/bsp.trace.json
2020.12.06 23:50:59 INFO  time: connected to build server in 1.16s
2020.12.06 23:50:59 INFO  Connected to Build server v1.4.6
2020.12.06 23:50:59 INFO  time: imported build in 0.61s
2020.12.06 23:51:18 INFO  time: indexed workspace in 18s
```
I don't know how to see the Language Server communication messages?
I didn't see any available `metals.trace.server` config as described here: https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
coc-java has `:CocCommand java.open.serverLog` to open eclipse.jdt.ls server log. See https://github.com/neoclide/coc-java#troubleshooting
Does coc-metals have similar command?

**Expected behavior**

Since 0.9.3, .sbt files are supported by Metals, see: https://github.com/scalameta/metals/issues/1838
so it should work.

**Installation:**

NVIM v0.4.4
coc-nvim v0.0.79
coc-metals v0.9.8
Metals v0.9.7
Linux

**Search terms**

.sbt support, build.sbt support

**Suggested solution**

I investigated the issue, and I think the .sbt files are simply ignored by `coc-metals`. 
See this: https://github.com/scalameta/coc-metals/blob/master/package.json#L52
only "scala" filetype is mentionned.
But, the new Metals support to .sbt files check directly in the language server for the extension, and treat *.sbt files differently from *.scala files. See: https://github.com/scalameta/metals/pull/1865/files#r461049391
coc-metals must also send information about build.sbt files to Metals, and it seems that's not the case right now.
I found a work-around. I read `:h g:coc_filetype_map` and added the following in my .vimrc/init.vim:
```
let g:coc_filetype_map = {
			\	'sbt' : 'scala'
			\}
```
Now, sbt files are considered like scala files, so they are treated the same way by the coc-metals extension, and finally on receiving their locations, Metals can process them appropriately.
After this change, .sbt files support works.

I think, a better fix would be to change coc-metals. Maybe adding a new filetype in `package.json`, taking inspiration from `coc-tsserver` extension: https://github.com/neoclide/coc-tsserver/blob/master/package.json#L43
I tried adding a new `filetype` like this:
```
    "rootPatterns": [
      {
        "filetype": "scala",
        "patterns": [
          "build.sbt",
          "build.sc",
          "build.gradle",
          "pom.xml"
        ]
      },
      {
        "filetype": "sbt",
        "patterns": [
          "build.sbt",
          "build.sc",
          "build.gradle",
          "pom.xml"
        ]
      }
    ],
```
But it didn't work because "sbt" is totally an unknown filetype. I guess the `g:coc_filetype_map` should be set somehow in the extension. I'm happy to work on a fix if the issue is confirmed on your side.

**Comment by ckipp01** [comment]
Thanks for the report @nicobao.

> I don't know how to see the Language Server communication messages?

You can see the LSP communication by creating trace files as explained [here on the Metals site](https://scalameta.org/metals/docs/contributors/getting-started.html#json-rpc-trace).

Ultimately I'm glad that you were able to find the root cause of your issue. However, instead of adding in another entry to the root patterns you suggest, it's much simpler and more common practice to simply have the following in your `.vimrc`:

```vim
au BufRead,BufNewFile *.sbt set filetype=scala
```

Ultimately, *.sbt files for all Vim purposes are just Scala files. Plus, treating these as Scala files will ensure that everyone has correct syntax highlight, Metals support etc.

Also in your root patters example, if the the second filetype would be sbt, then the patterns you have listed should really only hold the `build.sbt`, not all the others.

This is actually the first time I've ever seen this come up, as I assume most users have the above setting. I'd recommend that you add that to your `.vimrc`. I can make sure to include this in the readme to avoid any confusion.

**Comment by nicobao** [comment]
Thanks for your reply. I agree with your suggestion, I should have thought about that!
