### ISSUE TITLE
CocAction('format') freezes if .scakafmt.conf does not exist

### ISSUE THREAD

**Issue by simonmclean** [scalameta/coc-metals#383]
There's two ways to format.

- Using the `Format` command, which can be defined as `command! -nargs=0 Format :call CocAction('format')`
- Enabling format on save via the Coc config

The first method will result in nvim freezing if you don't have a `scakafmt.conf` in your project.

**To Reproduce** 

- Create a new project _without_ a `scakafmt.conf` 
- Try to format via the first method (CocAction). nvim freezes.
- Restart nvim and try formating via the second method (format on save). You'll get a prompt which explains the problem and offers to create an empty `scakafmt.conf`
- Choose to create the `scakafmt.conf`
- Now both methods work fine

**Expected behavior**

Instead of freezing, I'd expect the same prompt to appear when using the first method

**Installation:**

- Operating system: macOS
- nvim version: 0.44
- coc.nvim version: Don't know how to get this. Latest at time of posting 
- coc-metals extension version: 1.0.1
- Metals version: Don't know how to get this

**Comment by ckipp01** [comment]
Thanks for the report @simonmclean. I'm able to reproduce this, however coc-metals actually doesn't really do anything specific with the `window/showMessageRequest`, but coc.nvim itself should fully handle this. You can see in the [trace logs](https://scalameta.org/metals/docs/contributors/getting-started.html#json-rpc-trace) that the formatting request causes the show message request, but then coc.nvim seems to choke.

```
[Trace - 06:42:11 PM] Received request 'textDocument/formatting - (14)'
Params: {
  "textDocument": {
    "uri": "file:///Users/ckipp/Documents/scala-workspace/tester/src/main/scala/example/Main.scala"
  },
  "options": {
    "tabSize": 2,
    "insertSpaces": true
  }
}


[Trace - 06:42:11 PM] Sending request 'window/showMessageRequest - (2)'
Params: {
  "actions": [
    {
      "title": "Create .scalafmt.conf"
    },
    {
      "title": "Not now"
    },
    {
      "title": "Don\u0027t show again"
    }
  ],
  "type": 1,
  "message": "Unable to format since this workspace has no .scalafmt.conf file. To fix this problem, create an empty .scalafmt.conf and try again."
}
```

Are you able to report this issue upstream to coc.nvim as there really isn't anything on the coc-metals side that I think we can do.

**Comment by ckipp01** [comment]
Funny enough, after it freezes and then I kill it, _then_ it shows up...

```
client coc abnormal exit with: -1
Unable to format since this workspace has no .scalafmt.conf file. To fix this probl
em, create an empty .scalafmt.conf and try again.
(1)Create .scalafmt.conf, (2)Not now, (3)Don't show again:
```

**Comment by simonmclean** [comment]
Okay, I've opened an issue with coc https://github.com/neoclide/coc.nvim/issues/2899

**Comment by ckipp01** [comment]
I tested out their solution with using `CocActionAsync` instead, and that does indeed work, so I'll update the example configuration, and I'd suggest to use that.
