### ISSUE TITLE
Insert inferred type

### ISSUE THREAD

**Issue by otto-dev** [scalameta/coc-metals#401]
I don't think this is possible yet using `coc-metals`, but please correct me if I'm wrong. Metals provides a command to insert the inferred type for a variable: https://scalameta.org/metals/docs/integrations/new-editor.html#insert-inferred-type-of-a-value

Is it possible to utilize this using `coc-metals`, or could it be made possible?

**Comment by ckipp01** [comment]
Hey @otto-dev! Thanks for the question. This is actually already doable via `coc-metals` utilizing code actions.

![2021-06-12 18 23 16](https://user-images.githubusercontent.com/13974112/121782741-5de3fa00-cbab-11eb-8766-f04ecd0ab2c4.gif)

The mapping I'm using can be found here:

https://github.com/scalameta/coc-metals/blob/b54d19487058efafd24d4e8912d1970cd430491e/coc-mappings.vim#L100

**Comment by otto-dev** [comment]
Amazing! Thanks for the instructions, and the link for finding out more.

**Comment by otto-dev** [comment]
Sorry to get back to this, but I can't get it to work. Any hints how I could work on fixing this? Is this an upstream issue?

![DeepinScreenshot_select-area_20210613125811](https://user-images.githubusercontent.com/44302748/121793911-101ccf80-cc47-11eb-93a7-5033838d16d8.png)

**Comment by otto-dev** [comment]
Okay, for others, this works for me:

```
" Remap for do codeAction of current line
xmap <Space>a  <Plug>(coc-codeaction-selected)
```

I have to have a selection on the variable name, which can be as much as one character. So in my case, I have to press `v<Space>a`. You can use something other than `<Space>` of course. Things like `<Plug>(coc-codeaction)` in normal mode don't work for me.

Instead I'm using this trick to get the right suggestion depending on what my cursor is on in normal mode:
```
nmap <Space>a  v<Plug>(coc-codeaction-selected)
```

**Comment by otto-dev** [comment]
Issue: When I use `Scala 3` sources, there is a only 1-2 second window a few seconds after `vim` startup where I can trigger the `Insert type annotation` code action, which executes correctly. Then it stops working. Upstream issue: https://github.com/scalameta/metals/issues/2875

**Comment by ckipp01** [comment]
> Okay, for others, this works for me:
> 
> ```
> nmap <Space>a  <Plug>(coc-codeaction-cursor)
> ```
> 
> This works for selections:
> 
> ```
> xmap <Space>a  <Plug>(coc-codeaction-selected)
> ```

Glad you got it to work. Yea there are multiple different ways to trigger this.

> Actually, this appear to only work for primitive types. Upstream issue: scalameta/metals#2875

Answered over there.
