### ISSUE TITLE
.bloop folder grows without boundaries (bloop-bsp-clients-classes)

### ISSUE THREAD

**Issue by arbitrary-dev** [scalameta/coc-metals#410]
**Describe the bug**

Each new run of vim + coc-metals results in new `bloop-bsp-clients-classes` entries which are identical to the previous ones:

```
$ du -sh .bloop/core/bloop-bsp-clients-classes/* 
712K	.bloop/core/bloop-bsp-clients-classes/classes-Metals-5TfFX5RASPeyHEOh-O7kGQ==
712K	.bloop/core/bloop-bsp-clients-classes/classes-Metals-VnEP2HueTwu_JQsGeGv7pg==
712K	.bloop/core/bloop-bsp-clients-classes/classes-Metals-ZU6uaWGiQ-eReOpykI5IaQ==
424K	.bloop/core/bloop-bsp-clients-classes/test-classes-Metals-5TfFX5RASPeyHEOh-O7kGQ==
424K	.bloop/core/bloop-bsp-clients-classes/test-classes-Metals-VnEP2HueTwu_JQsGeGv7pg==
424K	.bloop/core/bloop-bsp-clients-classes/test-classes-Metals-ZU6uaWGiQ-eReOpykI5IaQ==
```

**To Reproduce**

1. Open project in `vim`
2. Close project
3. Repeat 1-2
4. Observe `.bloop/module/bloop-bsp-clients-classes`

**Expected behavior**

Classes reused and no compilation initiated on repeated project opens

**Installation**

- Operating system: Linux
- Vim version: 8.2 8020814
- coc.nvim version: 0.0.80-2cece2600a
- coc-metals extension version: 1.0.6
- Metals version: 0.10.4

**Comment by ckipp01** [comment]
Closing this in favor of the one you created in https://github.com/scalameta/metals/issues/3020
