### ISSUE TITLE
Is it possible to use an older version of coc-metals for a project that uses scala 2.11.8

### ISSUE THREAD

**Issue by cheonhyangzhang** [scalameta/coc-metals#420]
Hi 
I am working on a legacy repo that is still using scala 2.11.8, 
when I start coc metals I got the error 
```
You are using Scala version 2.11.8, which is not supported in this version of Metals. Please upgrade to Scala version 2.12.14 or alternatively to legacy Scala 2.11.12.
```

is it possible to use an older version of coc-metals so that it works with scala 2.11.8?

**Comment by ckipp01** [comment]
Hi @cheonhyangzhang, so using an old version of @cheonhyangzhang is difficult, especially depending on how you install it. The short answer is that even with an old version of `coc-metals`, you'll still get this warning. 2.11.8 is an _extremely_ old version of Scala that has been deprecated for a long time in Metals.

If possible are you able to just bump from 2.11.8 to 2.11.12? That update shouldn't really break anything and you'll then get rid of the warning. To be honest, I'm not even sure what Metals version does support 2.11.8, if any.

**Comment by cheonhyangzhang** [comment]
thanks @ckipp01 for the info

I talked to the repo owner, fortunately was able to upgrade to 2.11.12 and it works fine now!
