### ISSUE TITLE
Exception Unknown function: coc#util#jumpTo

### ISSUE THREAD

**Issue by oschrenk** [scalameta/coc-metals#426]
**Describe the bug**

When trying to execute `CocCommand metals.tvp` I'm getting 

```
[coc.nvim]: UnhandledRejection: request error nvim_call_function - Vim:E117: Unknown
 function: coc#util#jumpTo
Error
    at ON.request (/Users/oliver/.tilde/dotfiles/.config/nvim/plugged/coc.nvim/build
/index.js:30:34613)
    at ON.call (/Users/oliver/.tilde/dotfiles/.config/nvim/plugged/coc.nvim/build/in
dex.js:33:3671)
    at o.<anonymous> (/Users/oliver/.tilde/dotfiles/.config/nvim/plugged/coc-metals/
lib/index.js:14:2546)
    at Generator.next (<anonymous>)
    at s (/Users/oliver/.tilde/dotfiles/.config/nvim/plugged/coc-metals/lib/index.js
:14:123)
```

**To Reproduce** Steps to reproduce the behavior:

1. Have Scala project
have:
vim version: NVIM v0.6.0-dev+nightly-380-gdf33f30e8
node version: v12.20.2
coc.nvim version: 0.0.80-3086844413
coc.nvim directory: /Users/oliver/.tilde/dotfiles/.config/nvim/plugged/coc.nvim
term: tmux
platform: darwin

Install coc-metals via

`Plug 'scalameta/coc-metals', {'do': 'yarn install --frozen-lockfile'} `

Use

`nnoremap <silent> <space>t :<C-u>CocCommand metals.tvp<CR>` on project

Fail.

**Expected behavior**

Show tree
**Screenshots**

n/A

**Installation:**

vim version: NVIM v0.6.0-dev+nightly-380-gdf33f30e8
node version: v12.20.2
coc.nvim version: 0.0.80-3086844413
coc.nvim directory: /Users/oliver/.tilde/dotfiles/.config/nvim/plugged/coc.nvim
term: tmux
platform: darwin

main branch of coc-metals since I already needed to pull in for https://github.com/scalameta/coc-metals/issues/421

**Additional context**

**Search terms**

**Comment by ckipp01** [comment]
Thanks for the report @oschrenk! I shot in a PR that should fix that in #427. Looks like it was removed and replaced with another function.
