### ISSUE TITLE
Setting `metals.javaHome` causes CoC to exist abnormally

### ISSUE THREAD

**Issue by jsatk** [scalameta/coc-metals#47]
**Describe the bug**

When prompted to add a `metals.javaHome` after opening a tmp Scala file it exits "abnormally" with status code of -1.

Example of what's in my `coc-settings.json`:

```jsonc
  "metals.javaHome": "/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/"
```

**To Reproduce** Steps to reproduce the behavior:

1. `vim /tmp/foo.scala`
2. Notice prompt about Java Home not being configured.
3. Press 1 to open `coc-settings.json`.
4. In a shell run `echo $JAVA_HOME | pbcopy # macOS required for pbcopy. Otherwise just copy the printed path`
5. Paste clipboard into `metals.javaHome` in `coc-settings.json`.
6. Get reload prompt.
7. Press 1 to reload.
8. Experience error.

**Expected behavior**

1. `vim /tmp/foo.scala`
2. Notice prompt about Java Home not being configured.
3. Press 1 to open `coc-settings.json`.
4. In a shell run `echo $JAVA_HOME | pbcopy # macOS required for pbcopy. Otherwise just copy the printed path`
5. Paste clipboard into `metals.javaHome` in `coc-settings.json`.
6. Get reload prompt.
7. Press 1 to reload.
8. No error and everything works well.

**Installation:**

- Operating system: macOS
- Vim 8
- coc-metals extension version: The latest
- Metals version: 0.8

**Search terms**

java_home, javaHome

**Comment by ckipp01** [comment]
Hey @jsatk, thanks for reporting!

We recently changed some things about finding your java home settings as we were combining the common parts of the vs code and coc-metals internals into a shared package. For example, I just tested what you have up above, and with the latest changes to master, I didn't have an issue.

When you say `The latest`, do you mean latest stable release or latest master? If you are on the latest stable, can you do a `:CocUninstall coc-metals` and then try `:CocInstall https://github.com/scalameta/coc-metals`, which will pull in the latest master? I'm assuming this will fix the problem you're seeing, but if not, report back.

**Comment by jsatk** [comment]
> Hey @jsatk, thanks for reporting!
> 
> We recently changed some things about finding your java home settings as we were combining the common parts of the vs code and coc-metals internals into a shared package. For example, I just tested what you have up above, and with the latest changes to master, I didn't have an issue.
> 
> When you say `The latest`, do you mean latest stable release or latest master? If you are on the latest stable, can you do a `:CocUninstall coc-metals` and then try `:CocInstall https://github.com/scalameta/coc-metals`, which will pull in the latest master? I'm assuming this will fix the problem you're seeing, but if not, report back.

I'm using the latest stable. 😄 

I'll trust that this is fixed in `master`. I use this for work and value stability over bleeding-edge features so I'll happily wait for this to land in a stable release. 

Again, this isn't a major issue and only shows up when I try to write Scala in some throw away `tmp/foo.scala` file.

Thanks for reply.

**Comment by ckipp01** [comment]
Sounds good! You shouldn't have to wait too long for a new stable! If you do happen to hit on it again then, just jump back in here 👍
