### ISSUE TITLE
Persisted Errors even after compiling

### ISSUE THREAD

**Issue by vito-c** [scalameta/coc-metals#88]
**Describe the bug**
I am using sbt 0.13 and scala 2.11 so not sure if it's related to that but...
When I write an error it persists until I  physically `:e %` the file. Then the "gutter" error will go away.  Then if I add a comment or delete some white space the error shows up again so I `:w` the file error is still there then `:e %` and the gutter errors disappear. I'm using nvim and I updated coc last night.

**Comment by ckipp01** [comment]
Thanks for the report.

I created a new project with sbt 0.13.18 and 2.11.10. I made sure there was some issues, had the gutter signs appear, fixed them, and then they went away. I'm currently unable to reproduce this. Are you able to provide a minimal project where this is happening consistently?

Also, when this happens, if you look at your diagnostics, `<space> a` if you have the default mappings, does it show that there are still actual diagnostics that aren't cleared, or is it just that the gutter sign won't go away?

**Comment by vito-c** [comment]
maybe it's related to this message I get whenever I start vim? `[coc.nvim] Failed to connect with build server, no functionality will work. See logs for more details.`

**Comment by vito-c** [comment]
I figured out the repro case:
If you change the `build.sbt` then the error will persist. Particularly the import errors. For example import something isn't included then update the build.sbt and the error won't go away. But then when I `:e %` it goes away until I edit the file.

**Comment by ckipp01** [comment]
If I understand what you explained, I still wasn't able to reproduce it.

Steps I following:
1. Create a simple sbt project
2. In main use `Instant` without importing add which adds the diagnostic issue
3. Change `build.sbt`
4. Go back to main, remove line with issue, and the diagnostic sign in the gutter goes away as expected.

Is this what you mean? If not can you try to give explicit steps to how this is happening for you?

**Comment by vito-c** [comment]
Steps:

1. Create a simple sbt project (0.13.x with 2.11.12)
2. In main import something that is not referenced in your build.sbt
3. You will see the diagnostic issue
4. update your build.sbt with the libraryDependency 
5. go to the main and see the errors `:e %` and the errors  go away
6. Then make some changes and the errors come back `:e %`   and they go away. 

I  updated again so I'll let you know  if the problems go away.

**Comment by ckipp01** [comment]
Thanks for the steps @vito-c.

So I just followed these exactly, and I'm still unable to reproduce this. In step 4, you should be getting a prompt that `sbt build needs to be re-imported`. Does this happen for you? And if so, are able to ensure that the dependency has been pulled in correctly?

**Comment by vito-c** [comment]
`sbt build needs to be re-imported`  I don't   know if I get this I tend to just reload sbt is that what you mean?

**Comment by ckipp01** [comment]
> sbt build needs to be re-imported I don't know if I get this I tend to just reload sbt is that what you mean?

I'm assuming this is the problem them. When you edit your build definition, you should get a prompt like the one below, which you'll want to `Import Changes`. If not, that information won't get "dumped" out for bloop, which means that bloop won't know about those dependencies, which means your diagnostics will remain.

<img width="550" alt="Screenshot 2020-02-24 at 19 31 17" src="https://user-images.githubusercontent.com/13974112/75180336-45dd3280-573c-11ea-8e18-c51eb4b030c0.png">

To confirm this, try it again, and if it doesn't prompt you, trigger your command menu and select `metals.build-import` which will do it manually. You should then see your diagnostics disappear.

<img width="474" alt=" diag" src="https://user-images.githubusercontent.com/13974112/75180545-b97f3f80-573c-11ea-93a0-fbc46e9bee30.png">

**Comment by ckipp01** [comment]
@vito-c just checking back in. Did you manage to get this figured out?

**Comment by vito-c** [comment]
@ckipp01 does `CocRebuild` do the same thing I think what's happening is my connection to the metals server times out or something? I still see this a bit so I will try to create a project at some point.

**Comment by vito-c** [comment]
how did you get the
`FUZZY > import build` ?

**Comment by ckipp01** [comment]
> @ckipp01 does CocRebuild do the same thing...

No, `CocRebuild` rebuilds the source for your coc extensions. There should be no reason to do that here.

> ...I think what's happening is my connection to the metals server times out or something? I still see this a bit so I will try to create a project at some point.

If you think this is happening, you can also try a `metals.build-connect` from the command window. This will connect back to the server. However, again, reading your situation, it seems like your not re-importing after a change to your build definition.

> how did you get the `FUZZY > import build` ?

If you have the recommended mappings you can trigger this with `<space> c`. It comes from this mapping.

```vim
" Show commands
nnoremap <silent> <space>c  :<C-u>CocList commands<cr>
```

**Comment by vito-c** [comment]
This was due to a sneaky autocommand I had hidden in my vimrc. :(
```
    augroup autotag " {{{
        autocmd!
        " need to cd to groot
        autocmd BufNewFile,BufRead,BufEnter * call UpdatePath()
    augroup END " }}}

    function! UpdatePath()
        let foo =  match(fnameescape(expand('%')), "fugitive://")
        if &buftype != 'terminal' && foo < 0
            set path&vim | let &path=rc#git#groot()['dir'] . '/**'
            execute 'cd' rc#git#groot()['dir']
        endif
    endfunction
```

**Comment by vito-c** [comment]
I'm closing this until I can get a test project seems like i''m the only one with the issue so it's likely in my vimrc :D

**Comment by ckipp01** [comment]
> I'm closing this until I can get a test project seems like i''m the only one with the issue so it's likely in my vimrc :D

Sounds good! If you end up getting a minimal reproduction that I can look at, please let me know!
