### ISSUE TITLE
Metals does not recognise build.sbt / sets wrong directory as workspace

### ISSUE THREAD

**Issue by marrs** [scalameta/coc-metals#91]
For some reason, coc-metals won't run correctly in my scala project.  I have demonstrated that there is nothing wrong with the project itself by duplicating the project in a different directory and demonstrating coc-metals to work fine with it.  I've also used unix diff to make sure that the two projects are identical (with the exception of some reasonable differences to `metals.log` and `metals.lock.db`).

Initially, during my debugging, I discovered that the versions of sbt and scala that I was running were too old and these were probably the original cause of my troubles, however my original project still does not work with coc-metals in the following manner:

From within my project root (which I'm calling `/path/to/myproject`), running `vim build.sbt` produces *no behaviour from coc whatsoever*.

I can get coc to try and run metals if I open a scala file (e.g. `vim /path/to/myproject/src/main/main.scala`).  In this case, coc-metals gets confused about where the project root is.  Instead of creating a `.metals` directory in `/path/to/myproject` (where my build.sbt is located), it instead puts it in the directory above, `/path/to`.  it does not try to import the build.  It simply stops with a message:
> no build target for:/path/to/myproject/src/main/main.scala

This message can be found in the log file located at `/path/to/.metals/metals.log`.  The complete log is reproduced below:
> INFO  started: Metals version 0.8.0 in workspace '/path/to'
INFO  time: initialize in 2.25s
WARN  no build tool detected in workspace '/path/to'. The most common cause for this problem is that the editor was opened in the wrong working directory, for example if you use sbt then the workspace directory should contain build.sbt. 
WARN  no build target for: /path/to/myproject/src/main/main.scala

I've tried cleaning the project by deleting, `target/`, `project/target`, `project/project/target`, and `../.metals`, but this has not helped.  I've also tried uninstalling and reinstalling coc and coc-metals.  I've tried running `sbt reload`.

I've also tried copying the `.metals` and `.bloop` directories from my working version of the project to the original, but they seem to be ignored.

I've also tried turning around, touching the ground, and drinking 3 bloody marys.

The only thing I can imagine is that coc-metals has somehow cached my original workspace directory and refuses to let go of it.  Any help getting to the bottom of this would be appreciated

**Comment by ckipp01** [comment]
Thanks for the report!

Are you using the last stable release of coc-metals or are you using the master branch? If you aren't using the master branch, you may want to give it a try as I think #90 could be the problem that you are running into. You can read more about it [here](https://github.com/neoclide/coc.nvim/wiki/Using-workspaceFolders).

More than likely coc.nvim is either picking up a `.git` directory or something in `path/to/` and marking that as your project root. If you don't want to switch to master, you can also just manually add the following to your `:CocConfig`, which should hopefully fix the issue.

```js
"coc.preferences.rootPatterns": ["build.sbt", "build.sc", "build.grade", "pom.xml"]
```
If you are already on the latest Master, then we have a whole other issue.

Try that and get back to me.

**Comment by marrs** [comment]
That did the trick.  I am running the latest stable release so i tried the `CocConfig` option.

I don't know if I was supposed to issue the above config as a command (i.e. `:CocConfig "coc.preferences.rootPatterns": ["build.sbt", "build.sc", "build.grade", "pom.xml"]`), but that didn't work, so I added the json to the file manually, which did work.

My `~/.vim/coc-settings.json` now looks like:
```
{
    "coc": {
        "preferences": {
            "rootPatterns": ["build.sbt", "build.sc", "build.grade", "pom.xml"]
        }
    }
}
```

Many thanks for the help.  This sets me up nicely for work tomorrow :)

**Comment by marrs** [comment]
As an aside, my Scala project is running the API layer of a larger project, so there is indeed a `.git` directory where it thought the project root was.

**Comment by shwangdev** [comment]
I also confronted with this problem. And I was using Emacs. 
Any suggestions on Emacs?

**Comment by shwangdev** [comment]
> As an aside, my Scala project is running the API layer of a larger project, so there is indeed a `.git` directory where it thought the project root was. I guess that explains the cause of the issue

@marrs And how to work this problem out? I am facing the problem in Emacs too.

**Comment by endrebak** [comment]
Yeah, metals sets the wrong directory as the root of the build for me too :/

**Comment by ckipp01** [comment]
@shwangdev I'd recommend asking how to see the root patters on the lsp-mode gitter. They will probably have a better idea how to set it for emacs.
